# Generated by Django 4.0.3 on 2022-04-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_value', models.CharField(max_length=25, verbose_name='Ціна')),
                ('pc_description', models.CharField(max_length=200, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Ціни',
                'verbose_name_plural': 'Ціни',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(max_length=200, verbose_name='Послуга')),
                ('pt_old_price', models.CharField(max_length=200, verbose_name='Стара ціна ')),
                ('pt_new_price', models.CharField(max_length=200, verbose_name='Нова ціна')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
